### ISSUE TITLE
Add Multiple FreeTime Tags At Once

### ISSUE THREAD

**Issue by nyankoclaws** [AY2324S2-CS2103T-F11-4/tp#101]

**Comment by nyankoclaws** [comment]
Check for adding duplicate tags

**Comment by donwong2308** [comment]
Example: 
If there is a current free time tag Mon:1300-1400 and I want to add Mon:1300-1500.
Since the new tag overlaps, the current free time tag should be removed and the new free time tag (Mon:1300-1500) will be added in.

But if the current tag is Mon:1200-1300 and the new tag is Mon:1300-1400, then the contact will have both the free time tags, AKA: Mon:1200-1300 and Mon:1300-1400 (tldr no need to merge intervals)
